    # API server listen address
    # Defauls to: ":8080" which will listen on all avalable interfaces.
listen: :8080

    # HTTP Server middleware environment
    # Available values:
    #   dev
    #       development environment
    #   prod
    #       production environment
    #
    # Defaults to: prod
middleware: dev

    # Private key path - used for JWT signing
    # Defaults to: /etc/useradm/rsa/private.pem
#server_priv_key_path: /etc/useradm/rsa/private.pem

    # JWT issuer ('iss' claim)
    # Defaults to: mender.useradm
#jwt_issuer: mender.useradm

    # JWT expiration in seconds ('exp' claim)
    # Defaults to: "604800" (one week)
#jwt_exp_timeout: 604800
